
const products=[
    {name:"redmi",brand:"xiaomi",price:30000,color:"black"},
    {name:"sumsung",brand:"xiaomi",price:40000,color:"black"},
    {name:"galaxy",brand:"xiaomi",price:50000,color:"black"},
    {name:"sumsung",brand:"xiaomi",price:60000,color:"black"},
    {name:"sumsung",brand:"xiaomi",price:70000,color:"black"},
    {name:"iphone",brand:"xiaomi",price:80000,color:"black"},
    {name:"oppo",brand:"xiaomi",price:90000,color:"black"},
    {name:"sumsung",brand:"xiaomi",price:10000,color:"black"},
    {name:"redmi",brand:"xiaomi",price:20000,color:"black"},
    {name:"sumsung",brand:"xiaomi",price:30000,color:"black"},
    {name:"oppo",brand:"xiaomi",price:40000,color:"black"},
    {name:"endroyed",brand:"xiaomi",price:50000,color:"black"},
    {name:"redmi",brand:"xiaomi",price:60000,color:"black"},
    {name:"redmi",brand:"xiaomi",price:70000,color:"black"},
    {name:"redmi",brand:"xiaomi",price:80000,color:"black"},
    {name:"redmi",brand:"xiaomi",price:90000,color:"black"},
    {name:"redmi",brand:"xiaomi",price:30000,color:"black"},
    {name:"redmi",brand:"xiaomi",price:30000,color:"black"},
    {name:"redmi",brand:"xiaomi",price:30000,color:"black"},
    {name:"redmi",brand:"xiaomi",price:30000,color:"black"},
]